### ISSUE TITLE
What's the reasoning behind filtering packages that do not have a dev-repo field?

### ISSUE THREAD

**Issue by kit-ty-kate** [tarides/opam-monorepo#341]
https://github.com/tarides/opam-monorepo/blob/eec0b8302937949dda1e80b73961702f6c901bca/lib/duniverse.mli#L66

This took 2 hours out of my life to figure out why it wasn't adding a custom package to my mirage project.
I'm not sure I understand the reasoning behind this. This seems to have been added in https://github.com/tarides/opam-monorepo/pull/131 but I'm not sure to understand why opam-monorepo silently ignores packages that do not have a `dev-repo` field.

**Comment by Leonidas-from-XIV** [comment]
I am not sure myself but I believe I have a decent hypothesis why this happens based on this test:

https://github.com/tarides/opam-monorepo/blob/5e22093f3784202672424acf5fbec11cf74cd929/test/test_duniverse.ml#L153-L169

`opam-monorepo` only supports one tarball per `dev-repo`, because if there are multiple tarballs, their contents might have overlapping source trees (and in fact, all opam packages from the same dev-repo released with `dune-release` share the same tarball which contains the entire source tree), so it needs to pick one or decide how to merge multiple source trees (which I would say is quite difficult, especially if the tarballs correspond to different versions of the dev-repo). The way it does so is by determining the `dev-repo`, but if they are missing the field, then it can't figure out which tarballs to aggregate.

It might be useful to display a warning if a package is missing the `dev-repo`, however this might be printing a lot of warnings for conf-packages or similar, so it would need to make sure to only warn on "normal" packages.

**Comment by kit-ty-kate** [comment]
> It might be useful to display a warning if a package is missing the `dev-repo`, however this might be printing a lot of warnings for conf-packages or similar, so it would need to make sure to only warn on "normal" packages.

`conf` packages usually have the `conf` flag so they could be easily filtered off this way.

**Comment by Leonidas-from-XIV** [comment]
That's true; certainly worth a try implementing a warning to see whether it will output some useful messages.
